//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moso.NetworkM.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ADInfo
    {
        public ADInfo()
        {
            this.MainInfo = new HashSet<MainInfo>();
        }
    
        public string AdAcount { get; set; }
        public string AdDisplay { get; set; }
        public string AdCode { get; set; }
        public short DelFlag { get; set; }
    
    [JsonIgnore]
        public virtual ICollection<MainInfo> MainInfo { get; set; }
    }
}
