//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moso.NetworkM.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MainInfo
    {
        public MainInfo()
        {
            this.PermissionInfo = new HashSet<PermissionInfo>();
        }
    
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string StaffName { get; set; }
        public string EAddress { get; set; }
        public string AdAcount { get; set; }
        public string AdCode { get; set; }
        public string CompName { get; set; }
        public string Ip { get; set; }
        public string MacAddress { get; set; }
        public string PCAsset { get; set; }
        public string ScreenAsset { get; set; }
        public short DelFlag { get; set; }
        public string SName { get; set; }
    
    [JsonIgnore]
        public virtual ADInfo ADInfo { get; set; }
    [JsonIgnore]
        public virtual StaffInfo StaffInfo { get; set; }
    [JsonIgnore]
        public virtual ICollection<PermissionInfo> PermissionInfo { get; set; }
    [JsonIgnore]
        public virtual EmailInfo EmailInfo { get; set; }
    }
}
