//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moso.NetworkM.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class O_ManagerInfo_ActionInfo
    {
        public int Id { get; set; }
        public int ManagerInfo_Id { get; set; }
        public int ActionInfo_Id { get; set; }
        public bool IsPass { get; set; }
    
    [JsonIgnore]
        public virtual ActionInfo ActionInfo { get; set; }
    [JsonIgnore]
        public virtual ManagerInfo ManagerInfo { get; set; }
    }
}
