//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moso.NetworkM.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionInfo
    {
        public PermissionInfo()
        {
            this.MainInfo = new HashSet<MainInfo>();
        }
    
        public int PId { get; set; }
        public string PName { get; set; }
        public string PRemark { get; set; }
        public Nullable<System.DateTime> PSubTime { get; set; }
        public short DelFlag { get; set; }
    
    [JsonIgnore]
        public virtual ICollection<MainInfo> MainInfo { get; set; }
    }
}
