//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moso.NetworkM.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInfo
    {
        public RoleInfo()
        {
            this.ManagerInfo = new HashSet<ManagerInfo>();
            this.ActionInfo = new HashSet<ActionInfo>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Remark { get; set; }
        public string Sort { get; set; }
        public short DelFlag { get; set; }
    
    [JsonIgnore]
        public virtual ICollection<ManagerInfo> ManagerInfo { get; set; }
    [JsonIgnore]
        public virtual ICollection<ActionInfo> ActionInfo { get; set; }
    }
}
