//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moso.NetworkM.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInfo
    {
        public StaffInfo()
        {
            this.MainInfo = new HashSet<MainInfo>();
        }
    
        public string EmpId { get; set; }
        public string StaffName { get; set; }
        public string Company { get; set; }
        public string Depart { get; set; }
        public string Position { get; set; }
        public string Floor { get; set; }
        public short DelFlag { get; set; }
    
    [JsonIgnore]
        public virtual ICollection<MainInfo> MainInfo { get; set; }
    }
}
